### ISSUE TITLE
--env=TERM=unknown breaks things

### ISSUE THREAD

**Issue by pshem** [cloudius-systems/osv-apps#66]
I think there is an issue in how OSv combines commandlines - this method is not immune to special characters. When creating an image made of multiple parts, such as `image=python3x,httpserver,mysql`, `--env=TERM=unknown` is treated as a flag for the previous program in the image. Creating an image made of these parts in a different order, `image=httpserver,python3x,mysql`, works just fine:

![Selectionshot_2019-03-13_17:14:33](https://user-images.githubusercontent.com/26800787/54299800-87b8ab80-45b3-11e9-8f46-9f08e058fadf.png)

The fact that python3's output is shown before mysql'd output doesn't affect functionality. Python3x uses `--env=TERM=unknown` as part of it's cmdline.

**Comment by wkozaczuk** [comment]
I tend to explicitly set command line when building multiple apps into one image just to avoid these kind of problems. 

I would also like to emphasize another point. I see you are trying to build OSv images made of 3 apps possibly with testing/learning motivation in mind. Please note that OSv is a unikernel that by design is intended to run _single Linux application_ as long it does not use fork() or other not implemented functions from Linux ABI. So while running more than one applications is possible (as you can see) it is **strongly discouraged in production** as for example in your case crash in mysql (some sort of invalid memory access) will bring whole instance down including your python app and vice versa. It happens because OSv does not provide any strong isolation isolation between apps and kernel like traditional OS-es do. 

Now having said that it is fine to add httpserver app because it is really very light single-threaded system app designed to optionally run along kernel threads to provide monitoring and administrative functions. In your case I would advise having two OSv instances - python,httpserver and httpserver,mysql.

For more discussion about multi-application support in OSv and its implications please see this - https://groups.google.com/forum/#!msg/osv-dev/7lx2dxpLMdk/q9Ctw9V8AgAJ

BTW are you familiar with [capstan](https://github.com/mikelangelo-project/capstan)?

**Comment by nyh** [comment]
Let's move this discussion to the mailing list, so I'm closing this issue. Also the question is not really related to the osv-apps repository, but more to the scripts/build script, part of the main osv repository.
But since I'm already here, I'll try to answer. 

I don't understand what you **expected** `scripts/build image=python3x,httpserver,mysql, --env=TERM=unknown` to do, and what it actually did. The `scripts/build`'s `image=` option takes a comma-separate list of "modules" (i.e., different packages usually from the osv-apps repository) and builds an image containing these packages and possibly other ones which they depend on. You cannot pass to it "--env=TERM=unknown" - that is not an image name!

Looking at the build/script code, it has the command:
```sh
fs_type=$fs_type jdkbase=$jdkbase ARCH=$arch mode=$mode OSV_BASE=$SRC OSV_BUILD_PATH=$OSV_BUILD_PATH scripts/module.py $j_arg build -c $modules $usrskel_arg $no_required_arg
```
This has a bug that $modules is not quoted. So if the image=... has a *space* character, this will get confused. I'll send a patch for this. But in any case it won't make "--env..." the way you did it, work.

**Comment by pshem** [comment]
@nyh I should have put in more visual separation in my explanations. I didn't pass `--env=TERM=unknown` to the build script. You can see that on the included screenshot. I don't think a fix quoting "$modules" solves the issue, because I didn't have any spaces in `image=`.

The two situations from the screenshot are:
- `image=python3x,httpserver,mysql` fails. It's cmdline is most likely `/usr/bin/mysqld --datadir=/usr/data --user=root&--env=TERM=unknown/python3`;
- `image=httpserver,python3x,mysql` works fine. It's resulting cmdline is `--env=TERM=unknown/python3&/usr/bin/mysqld --datadir=/usr/data --user=root`

The issue is that a part of `python3x`'s command line, `--env=TERM=unknown`, is treated by OSv as if it were a shared object to be loaded unless it is at the beginning of the resulting command line.

@wkozaczuk Capstan wouldn't work for us because we needed to fix python3 first. If it weren't a university project, I'd probably use Capstan for deploying OSv in production, but this project will end at Proof of Concept. Testing all elements on the same unikernel, while orthogonal to the intended use of a unikernel, is mainly a consequence of `run.py` only allowing a single OSv instance to run simultaneously while being the easiest OSv execution method to setup.
